[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Stuart <stuart@accentdesign.co.uk>"]

[tool.poetry.dependencies]
python = "^3.11"
accentdatabase = "^0.0.5"
accentnotifications = {extras = ["smtp"], version = "^0.0.2"}
alembic = "^1.10.2"
asyncpg = "^0.27.0"
fastapi = {extras = ["all"], version = "^0.95.0"}
fastapi-users = {extras = ["sqlalchemy"], version = "^10.4.1"}
passlib = {extras = ["argon2", "bcrypt"], version = "^1.7.4"}
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
sentry-sdk = {extras = ["fastapi"], version = "^1.17.0"}
typer = {extras = ["all"], version = "^0.7.0"}

[tool.poetry.group.dev.dependencies]
autoflake = "^2.0.2"
black = "^23.1.0"
flake8 = "^6.0.0"
httpx = "^0.23.3"
isort = "^5.12.0"
mypy = "^1.1.1"
pytest = "^7.2.2"
pytest-asyncio = "^0.21.0"
pytest-mock = "^3.10.0"

[tool.mypy]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "app.database.migrations.*"
ignore_errors = true

[tool.black]
line-length = 88
exclude = '''
  /(
    migrations
  )/
'''

[tool.isort]
profile = "black"
extend_skip = [
  'migrations'
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
